package com.danqiu.myapplication.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.danqiu.myapplication.bean.UserBean;
import com.danqiu.myapplication.bean.ClassBean;

import com.danqiu.myapplication.greendao.UserBeanDao;
import com.danqiu.myapplication.greendao.ClassBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig classBeanDaoConfig;

    private final UserBeanDao userBeanDao;
    private final ClassBeanDao classBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        classBeanDaoConfig = daoConfigMap.get(ClassBeanDao.class).clone();
        classBeanDaoConfig.initIdentityScope(type);

        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        classBeanDao = new ClassBeanDao(classBeanDaoConfig, this);

        registerDao(UserBean.class, userBeanDao);
        registerDao(ClassBean.class, classBeanDao);
    }
    
    public void clear() {
        userBeanDaoConfig.clearIdentityScope();
        classBeanDaoConfig.clearIdentityScope();
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public ClassBeanDao getClassBeanDao() {
        return classBeanDao;
    }

}
