package com.danqiu.myapplication.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.danqiu.myapplication.bean.ClassBean;
import com.danqiu.myapplication.bean.UserBean;
import com.danqiu.myapplication.greendao.TestBean;

import com.danqiu.myapplication.greendao.ClassBeanDao;
import com.danqiu.myapplication.greendao.UserBeanDao;
import com.danqiu.myapplication.greendao.TestBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig classBeanDaoConfig;
    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig testBeanDaoConfig;

    private final ClassBeanDao classBeanDao;
    private final UserBeanDao userBeanDao;
    private final TestBeanDao testBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        classBeanDaoConfig = daoConfigMap.get(ClassBeanDao.class).clone();
        classBeanDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        testBeanDaoConfig = daoConfigMap.get(TestBeanDao.class).clone();
        testBeanDaoConfig.initIdentityScope(type);

        classBeanDao = new ClassBeanDao(classBeanDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        testBeanDao = new TestBeanDao(testBeanDaoConfig, this);

        registerDao(ClassBean.class, classBeanDao);
        registerDao(UserBean.class, userBeanDao);
        registerDao(TestBean.class, testBeanDao);
    }
    
    public void clear() {
        classBeanDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
        testBeanDaoConfig.clearIdentityScope();
    }

    public ClassBeanDao getClassBeanDao() {
        return classBeanDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public TestBeanDao getTestBeanDao() {
        return testBeanDao;
    }

}
